#!/bin/sh

set -e

if [ -z ${MACHINE_NAME} ]; then
  echo "Please set MACHINE_NAME"
  exit 1
fi

if [ -z ${MACHINE_EXPORT_AWS_ACCESS_KEY_ID} ]; then
  echo "Please set MACHINE_EXPORT_AWS_ACCESS_KEY_ID"
  exit 1
fi
export AWS_ACCESS_KEY_ID=${MACHINE_EXPORT_AWS_ACCESS_KEY_ID}

if [ -z ${MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY} ]; then
  echo "Please set MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY"
  exit 1
fi
export AWS_SECRET_ACCESS_KEY=${MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY}

if [ -z ${MACHINE_EXPORT_AWS_DEFAULT_REGION} ]; then
  echo "Please set MACHINE_EXPORT_AWS_DEFAULT_REGION"
  exit 1
fi
export AWS_DEFAULT_REGION=${MACHINE_EXPORT_AWS_DEFAULT_REGION}

if [ -z ${MACHINE_EXPORT_AWS_BUCKET} ]; then
  echo "Please set MACHINE_EXPORT_AWS_BUCKET"
  exit 1
fi
export AWS_BUCKET=${MACHINE_EXPORT_AWS_BUCKET}

echo "Downloading pre existing configuration"
aws --region ${MACHINE_EXPORT_AWS_DEFAULT_REGION} s3 cp s3://${MACHINE_EXPORT_AWS_BUCKET}/${MACHINE_NAME}.zip ./ > /dev/nul 2>&1 || exit 0

echo "Pre-existing configuration found"
echo "Importing ${MACHINE_NAME}"
machine-import ${MACHINE_NAME}.zip
# The permission isn't set properly on import
chmod 0600 /root/.docker/machine/machines/${MACHINE_NAME}/id_rsa

echo "deleting pre-existing machine"
docker-machine rm -y ${MACHINE_NAME}

aws --region ${MACHINE_EXPORT_AWS_DEFAULT_REGION} s3 rm s3://${MACHINE_EXPORT_AWS_BUCKET}/${MACHINE_NAME}.zip
