#!/bin/sh

/delete-machine || exit 1

echo "Creating docker-machine ${MACHINE_NAME:?required}"
docker-machine create \
    -d digitalocean \
    --digitalocean-access-token=${DIGITALOCEAN_ACCESS_TOKEN:?required} \
    ${MACHINE_NAME}

if [ $? == 0 ]; then
  echo "Exporting connection info to ${MACHINE_NAME}"
  machine-export ${MACHINE_NAME}

  echo "Uploading info to bucket"
  aws --region ${AWS_DEFAULT_REGION:?required} s3 cp ${MACHINE_NAME}.zip s3://${AWS_BUCKET:?required}
fi
