#!/bin/sh

if [ -z ${MACHINE_NAME} ]; then
  echo "Please set MACHINE_NAME"
  exit 1
fi

if [ -z ${DIGITALOCEAN_ACCESS_TOKEN} ]; then
  echo "Please set DIGITALOCEAN_ACCESS_TOKEN"
  exit 1
fi

if [ -z ${MACHINE_EXPORT_AWS_ACCESS_KEY_ID} ]; then
  echo "Please set MACHINE_EXPORT_AWS_ACCESS_KEY_ID"
  exit 1
fi
export AWS_ACCESS_KEY_ID=${MACHINE_EXPORT_AWS_ACCESS_KEY_ID}

if [ -z ${MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY} ]; then
  echo "Please set MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY"
  exit 1
fi
export AWS_SECRET_ACCESS_KEY=${MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY}

if [ -z ${MACHINE_EXPORT_AWS_DEFAULT_REGION} ]; then
  echo "Please set MACHINE_EXPORT_AWS_DEFAULT_REGION"
  exit 1
fi
export AWS_DEFAULT_REGION=${MACHINE_EXPORT_AWS_DEFAULT_REGION}

if [ -z ${MACHINE_EXPORT_AWS_BUCKET} ]; then
  echo "Please set MACHINE_EXPORT_AWS_BUCKET"
  exit 1
fi
export AWS_BUCKET=${MACHINE_EXPORT_AWS_BUCKET}

/delete-machine || exit 1

echo "Creating docker-machine ${MACHINE_NAME}"
docker-machine create \
    -d digitalocean \
    --digitalocean-access-token=${DIGITALOCEAN_ACCESS_TOKEN} \
    ${MACHINE_NAME}

if [ $? == 0 ]; then
  echo "Exporting connection info to ${MACHINE_NAME}"
  machine-export ${MACHINE_NAME}

  echo "Uploading info to bucket"
  aws --region ${MACHINE_EXPORT_AWS_DEFAULT_REGION} s3 cp ${MACHINE_NAME}.zip s3://${MACHINE_EXPORT_AWS_BUCKET}
fi
